In [1]:
import geopandas
import geodatasets

df = geopandas.read_file(geodatasets.get_path('nybb'))
df

,BoroCode,BoroName,Shape_Leng,Shape_Area,geometry
0,5,Staten Island,330470.010332,1.623820e+09,"MULTIPOLYGON (((970217.022 145643.332, 970227...."
1,4,Queens,896344.047763,3.045213e+09,"MULTIPOLYGON (((1029606.077 156073.814, 102957..."
2,3,Brooklyn,741080.523166,1.937479e+09,"MULTIPOLYGON (((1021176.479 151374.797, 102100..."
3,1,Manhattan,359299.096471,6.364715e+08,"MULTIPOLYGON (((981219.056 188655.316, 980940...."
4,2,Bronx,464392.991824,1.186925e+09,"MULTIPOLYGON (((1012821.806 229228.265, 101278..."

In [2]:
df.crs

<Projected CRS: EPSG:2263>
Name: NAD83 / New York Long Island (ftUS)
Axis Info [cartesian]:
- X[east]: Easting (US survey foot)
- Y[north]: Northing (US survey foot)
Area of Use:
- name: United States (USA) - New York - counties of Bronx; Kings; Nassau; New York; Queens; Richmond; Suffolk.
- bounds: (-74.26, 40.47, -71.8, 41.3)
Coordinate Operation:
- name: SPCS83 New York Long Island zone (US Survey feet)
- method: Lambert Conic Conformal (2SP)
Datum: North American Datum 1983
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich

In [3]:
str(df.geometry[0].__geo_interface__)[:200]

"{'type': 'MultiPolygon', 'coordinates': [(((970217.0223999023, 145643.33221435547), (970227.216003418, 145641.63360595703), (970273.9365844727, 145641.63360595703), (970323.2053833008, 145637.38598632"

In [4]:
df = df.to_crs(epsg=4326)
str(df.geometry[0].__geo_interface__)[:200]

"{'type': 'MultiPolygon', 'coordinates': [(((-74.05050806403247, 40.566422034161015), (-74.05047137128544, 40.56641738793831), (-74.05030321271761, 40.566417461703345), (-74.05012587375454, 40.56640588"

In [36]:
df.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [33]:
df.geometry.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [11]:
geodatasets.get_path('nybb')

'/Users/aj/Library/Caches/geodatasets/nybb_16a.zip.unzip/nybb_16a/nybb.shp'

In [34]:
# geopandas.read_file(geodatasets.get_path('geoda airbnb')).to_json(to_wgs84=True)

In [19]:
df

,community,shape_area,shape_len,AREAID,response_r,accept_r,rev_rating,price_pp,room_type,num_spots,...,crowded,dependency,without_hs,unemployed,income_pc,harship_in,num_crimes,num_theft,population,geometry
0,DOUGLAS,46004621.1581,31027.0545098,35,98.771429,94.514286,87.777778,78.157895,1.789474,38,...,1.8,30.7,14.3,18.2,23791,47,5013,1241,18238,"POLYGON ((-87.60914 41.84469, -87.60915 41.844..."
1,OAKLAND,16913961.0408,19565.5061533,36,99.200000,90.105263,88.812500,53.775000,1.850000,20,...,1.3,40.4,18.4,28.7,19252,78,1306,311,5918,"POLYGON ((-87.59215 41.81693, -87.59231 41.816..."
2,FULLER PARK,19916704.8692,None,37,68.000000,NaN,91.750000,84.000000,1.833333,6,...,3.2,44.9,26.6,33.9,10432,97,1764,383,2876,"POLYGON ((-87.62880 41.80189, -87.62879 41.801..."
3,GRAND BOULEVARD,48492503.1554,28196.8371573,38,94.037037,83.615385,92.750000,119.533333,1.533333,30,...,3.3,39.5,15.9,24.3,23472,57,6416,1428,21929,"POLYGON ((-87.60671 41.81681, -87.60670 41.816..."
4,KENWOOD,29071741.9283,23325.1679062,39,92.542857,88.142857,90.656250,77.991453,1.615385,39,...,2.4,35.4,11.3,15.7,35911,26,2713,654,17841,"POLYGON ((-87.59215 41.81693, -87.59215 41.816..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,MOUNT GREENWOOD,75584290.0209,48665.1305392,74,NaN,NaN,NaN,NaN,NaN,0,...,1.0,36.8,4.3,8.7,34381,16,1233,326,19093,"POLYGON ((-87.69646 41.70714, -87.69644 41.706..."
73,MORGAN PARK,91877340.6988,46396.419362,75,85.500000,96.666667,97.000000,67.933333,1.000000,5,...,0.8,40.3,10.8,15.0,27149,30,3998,912,22544,"POLYGON ((-87.64215 41.68508, -87.64249 41.685..."
74,OHARE,371835607.687,173625.98466,76,83.500000,100.000000,83.000000,38.500000,2.500000,2,...,3.6,30.3,10.9,7.1,25828,24,3423,1011,12756,"MULTIPOLYGON (((-87.83658 41.98640, -87.83658 ..."
75,EDGEWATER,48449990.8397,31004.8309456,77,94.429530,85.925676,94.540323,77.199510,1.582353,170,...,4.1,23.8,9.7,9.2,33385,19,4559,1409,56521,"POLYGON ((-87.65456 41.99817, -87.65456 41.998..."
76,EDISON PARK,31636313.7864,25937.226841,9,100.000000,95.000000,91.000000,25.000000,1.000000,1,...,1.1,35.3,7.4,6.5,40959,8,537,104,11187,"POLYGON ((-87.80676 42.00084, -87.80676 42.000..."

In [15]:
geodatasets.data.geoda.airbnb

{'url': 'https://geodacenter.github.io/data-and-lab//data/airbnb.zip',
 'license': 'NA',
 'attribution': 'Center for Spatial Data Science, University of Chicago',
 'name': 'geoda.airbnb',
 'description': 'Airbnb rentals, socioeconomics, and crime in Chicago',
 'geometry_type': 'Polygon',
 'nrows': 77,
 'ncols': 21,
 'details': 'https://geodacenter.github.io/data-and-lab//airbnb/',
 'hash': 'a2ab1e3f938226d287dd76cde18c00e2d3a260640dd826da7131827d9e76c824',
 'filename': 'airbnb.zip'}